# Generated by Django 5.1.4 on 2024-12-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
    ]
